- manifest.php
- model/provider/OauthProvider.php
- scripts/update/Updater.php
> Release 0.0.6

- README.md
- config/default/consumerStorage.conf.php
- config/default/oauth2Service.conf.php
- config/default/tokenService.conf.php
- config/default/userService.conf.php
- controller/TokenApi.php
- install/ontology/oauth-consumer.rdf
- manifest.php
- model/OAuthClient.php
- model/Oauth2Service.php
- model/OauthController.php
- model/bootstrap/OAuth2Type.php
- model/bootstrap/Oauth2SessionBuilder.php
- model/provider/OauthProvider.php
- model/provider/Provider.php
- model/provider/ProviderFactory.php
- model/storage/ConsumerStorage.php
- model/token/TokenService.php
- model/token/provider/TokenProvider.php
- model/token/provider/TokenProviderFactory.php
- model/user/UserService.php
- scripts/install/RegisterPublishingOauthAction.php
- scripts/tools/GenerateCredentials.php
- scripts/tools/ImportConsumer.php
- scripts/update/Updater.php
- views/templates/oauth/oAuthForm.tpl
> Release 0.2.1

- controller/TokenApi.php
- manifest.php
- scripts/update/Updater.php
> Release 0.2.2

- manifest.php
- model/bootstrap/Oauth2SessionBuilder.php
- scripts/update/Updater.php
> Release 1.0.1

- manifest.php
- model/bootstrap/OAuth2Type.php
- scripts/update/Updater.php
> Release 1.1.2

- manifest.php
- model/bootstrap/OAuth2Type.php
- model/provider/OauthProvider.php
- scripts/update/Updater.php
Depends on https://github.com/oat-sa/tao-core/pull/2068
> Feature/tao 7854/Accept http client options when instantiate http client

- manifest.php
- model/bootstrap/OAuth2Type.php
- model/provider/OauthProvider.php
- scripts/update/Updater.php
> Release 2.0.0

- manifest.php
- model/bootstrap/OAuth2AuthType.php
- model/bootstrap/OAuth2Type.php
- model/provider/Provider.php
- model/storage/ConsumerStorage.php
- model/storage/OauthCredentials.php
- scripts/update/Updater.php
- test/model/Oauth2TypeTest.php
https://oat-sa.atlassian.net/browse/TAO-8511
Depends on https://github.com/oat-sa/tao-core/pull/2214
> Feature/tao 8511/refactor basic auth type

- manifest.php
- model/bootstrap/OAuth2AuthType.php
- model/provider/Provider.php
- model/storage/ConsumerStorage.php
- model/storage/OauthCredentials.php
- scripts/install/RegisterPublishingOauthAction.php
- scripts/update/Updater.php
- test/model/Oauth2TypeTest.php
> Release 4.0.0

- manifest.php
- model/OAuthClient.php
- model/bootstrap/OAuth2AuthType.php
- model/bootstrap/OAuth2Type.php
- model/provider/OauthProvider.php
- scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-8741
Added possibility to provide curl options to GuzzleHttpClient
Main functionality not changed. Can be tested with any sync.
> TAO-8741. Curl options.

- manifest.php
- model/OAuthClient.php
- model/bootstrap/OAuth2AuthType.php
- model/bootstrap/OAuth2Type.php
- model/provider/OauthProvider.php
- scripts/update/Updater.php
> Release 4.1.0

- manifest.php
- model/OAuthClient.php
- scripts/update/Updater.php
> Release 4.1.1

- manifest.php
- model/OAuthClient.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/NEX-457
> Nex 457/logger verbosity improved

- manifest.php
- model/OAuthClient.php
- model/bootstrap/OAuth2AuthType.php
- model/provider/Provider.php
- model/storage/OauthCredentialsFactory.php
- model/storage/grant/AuthorizationCodeType.php
- model/storage/grant/ClientCredentialsType.php
- model/storage/grant/OauthCredentials.php
- model/storage/grant/PasswordType.php
- scripts/update/Updater.php
- test/model/OAuthClientTest.php
- test/model/Oauth2ServiceTest.php
- test/model/Oauth2TypeTest.php
- test/model/OauthCredentialsFactoryTest.php
> Release 5.0.0

- manifest.php
- model/OAuthClient.php
- model/provider/OauthProvider.php
- model/provider/ProviderFactory.php
- scripts/update/Updater.php
> Release 5.1.0

- manifest.php
- scripts/update/Updater.php
- test/model/OAuthClientTest.php
- test/model/Oauth2ServiceTest.php
- test/model/Oauth2TypeTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
> Feature/tdr 1/phpunit8 upgrade

- manifest.php
- scripts/update/Updater.php
- test/model/OAuthClientTest.php
- test/model/Oauth2ServiceTest.php
- test/model/Oauth2TypeTest.php
> Release 5.2.0

- manifest.php
- model/provider/Provider.php
- model/storage/grant/ClientCredentialsType.php
- scripts/update/Updater.php
- test/model/OAuthClientTest.php
- test/model/Oauth2ServiceTest.php
- test/model/Oauth2TypeTest.php
> Release 5.2.1

- manifest.php
- model/OAuthClient.php
https://oat-sa.atlassian.net/browse/NEX-1249
> Prevented loosing request params after refreshing access token

- manifest.php
- model/OAuthClient.php
- scripts/update/Updater.php
> Release 5.3.1

- model/OAuthClient.php
> Release 6.0.2

- model/storage/ConsumerStorage.php
- test/model/storage/ConsumerStorageTest.php
> Release 6.0.3

- composer.json
- model/OAuthClient.php
- model/storage/grant/OauthCredentials.php
- test/model/OauthCredentialsFactoryTest.php
> feat: Update composer.json with new league/oauth2-client version
